#!/bin/sh
#
# This file is part of the GNUstep XCTEST Library.
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.     See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; see the file COPYING.LIB.
# If not, see <http://www.gnu.org/licenses/> or write to the
# Free Software Foundation, 51 Franklin Street, Fifth Floor,
# Boston, MA 02110-1301, USA.
#
# xctest-bundle: wraps a shared library of tests as an XCTest bundle that
# xctest can load, for build systems other than gnustep-make (e.g. Meson):
#
#   xctest-bundle MyTests.xctest libMyTests.so [PrincipalClass]
#
# creates MyTests.xctest/MyTests (a copy of the library; MyTests.dll for a
# Windows DLL) and MyTests.xctest/Resources/Info-gnustep.plist, replacing
# any existing bundle.

set -e

if [ "$#" -lt 2 ] || [ "$#" -gt 3 ]; then
  echo "usage: $0 <Name.xctest> <shared library> [principal class]" >&2
  exit 2
fi

bundle=$1
library=$2
principal=${3:-}
name=$(basename "$bundle")
name=${name%.*}

if [ ! -f "$library" ]; then
  echo "$0: no such library: $library" >&2
  exit 1
fi

rm -rf "$bundle"
mkdir -p "$bundle/Resources"
# On Windows, NSBundle looks for <name>.dll.
case "$library" in
  *.dll|*.DLL) cp "$library" "$bundle/$name.dll" ;;
  *) cp "$library" "$bundle/$name" ;;
esac
{
  echo "{"
  echo "  NSExecutable = \"$name\";"
  echo "  CFBundleExecutable = \"$name\";"
  if [ -n "$principal" ]; then
    echo "  NSPrincipalClass = \"$principal\";"
  fi
  echo "}"
} > "$bundle/Resources/Info-gnustep.plist"
